apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
        - name: counter
          image: "kahootali/counter:1.1"
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 200Mi

          volumeMounts:
            - name: counter
              mountPath: /app/
      volumes:
        - name: counter
          persistentVolumeClaim:
            claimName: counter

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: counter
  labels:
    type: local
    name: counter
spec:
  volumeMode: Filesystem
  storageClassName: my-local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/counter"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: my-local-storage
  volumeMode: Filesystem
  volumeName: counter